//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbCyCEntities : DbContext
    {
        public dbCyCEntities()
            : base("name=dbCyCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPermiso> tblPermiso { get; set; }
        public virtual DbSet<tblPermisoDenegadoPorRol> tblPermisoDenegadoPorRol { get; set; }
        public virtual DbSet<tblRol> tblRol { get; set; }
        public virtual DbSet<tblConyugue> tblConyugue { get; set; }
        public virtual DbSet<tblEmpleo> tblEmpleo { get; set; }
        public virtual DbSet<tblEstatusDocumento> tblEstatusDocumento { get; set; }
        public virtual DbSet<tblEstatusSolicitud> tblEstatusSolicitud { get; set; }
        public virtual DbSet<tblReferencia> tblReferencia { get; set; }
        public virtual DbSet<tblSolicitud> tblSolicitud { get; set; }
        public virtual DbSet<tblTipoDocumento> tblTipoDocumento { get; set; }
        public virtual DbSet<tblDireccionAval> tblDireccionAval { get; set; }
        public virtual DbSet<tblDireccionCliente> tblDireccionCliente { get; set; }
        public virtual DbSet<tblDireccionReferencia> tblDireccionReferencia { get; set; }
        public virtual DbSet<tblRelSolicitudDocumento> tblRelSolicitudDocumento { get; set; }
        public virtual DbSet<tblRelUsuarioRol> tblRelUsuarioRol { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
        public virtual DbSet<tblAval> tblAval { get; set; }
        public virtual DbSet<tblCliente> tblCliente { get; set; }
    
        public virtual ObjectResult<SP_ADDUPD_USERS_Result> SP_ADDUPD_USERS(string usuario, string contrasena, string nombre, string apellidoPaterno, string apellidoMaterno, Nullable<int> idUsuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("apellidoPaterno", apellidoPaterno) :
                new ObjectParameter("apellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("apellidoMaterno", apellidoMaterno) :
                new ObjectParameter("apellidoMaterno", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADDUPD_USERS_Result>("SP_ADDUPD_USERS", usuarioParameter, contrasenaParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, idUsuarioParameter);
        }
    }
}
