//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccionAval
    {
        public int idDireccion { get; set; }
        public Nullable<int> idColonia { get; set; }
        public string calle { get; set; }
        public string direccion { get; set; }
        public string codigoPostal { get; set; }
        public string manzana { get; set; }
        public string lote { get; set; }
        public string numeroInterior { get; set; }
        public string numeroExterior { get; set; }
        public string cruzamientos { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> idAval { get; set; }
    
        public virtual tblAval tblAval { get; set; }
    }
}
