//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDireccion()
        {
            this.tblAval = new HashSet<tblAval>();
            this.tblCliente = new HashSet<tblCliente>();
            this.tblEmpleo = new HashSet<tblEmpleo>();
            this.tblReferencia = new HashSet<tblReferencia>();
        }
    
        public int idDireccion { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<int> idColonia { get; set; }
        public string calle { get; set; }
        public string direccion { get; set; }
        public string codigoPostal { get; set; }
        public string manzana { get; set; }
        public string lote { get; set; }
        public string numeroInterior { get; set; }
        public string numeroExterior { get; set; }
        public string cruzamientos { get; set; }
        public string comentarios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAval> tblAval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCliente> tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpleo> tblEmpleo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferencia> tblReferencia { get; set; }
    }
}
