//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleo()
        {
            this.tblConyugue = new HashSet<tblConyugue>();
            this.tblAval = new HashSet<tblAval>();
            this.tblCliente = new HashSet<tblCliente>();
        }
    
        public int idEmpleo { get; set; }
        public string nombreEmpresa { get; set; }
        public string departamento { get; set; }
        public string puesto { get; set; }
        public string giroEmpresa { get; set; }
        public string telefono { get; set; }
        public string ext { get; set; }
        public Nullable<int> idDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConyugue> tblConyugue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAval> tblAval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCliente> tblCliente { get; set; }
    }
}
