//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermisoDenegadoPorRol
    {
        public int idPermisoDenegado { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idPermiso { get; set; }
    
        public virtual tblPermiso tblPermiso { get; set; }
        public virtual tblRol tblRol { get; set; }
    }
}
