//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelSolicitudDocumento
    {
        public int idDocumento { get; set; }
        public Nullable<int> idEstatusDocumeto { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string imagenDocumento { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idAval { get; set; }
    
        public virtual tblEstatusDocumento tblEstatusDocumento { get; set; }
        public virtual tblSolicitud tblSolicitud { get; set; }
        public virtual tblTipoDocumento tblTipoDocumento { get; set; }
        public virtual tblAval tblAval { get; set; }
        public virtual tblCliente tblCliente { get; set; }
    }
}
