//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferencia
    {
        public int idReferencia { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string lada { get; set; }
        public byte[] celular { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idDireccion { get; set; }
    
        public virtual tblDireccion tblDireccion { get; set; }
        public virtual tblSolicitud tblSolicitud { get; set; }
    }
}
