//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelDocumentoAval
    {
        public int idRelDocumentoAval { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idAval { get; set; }
    
        public virtual tblAval tblAval { get; set; }
        public virtual tblDocumento tblDocumento { get; set; }
    }
}
