//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelSolicitudVendedor
    {
        public int idRelSolicitudVendedor { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idVendedor { get; set; }
    
        public virtual tblSolicitud tblSolicitud { get; set; }
        public virtual tblVendedor tblVendedor { get; set; }
    }
}
