//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelUsuarioRol
    {
        public int idRelUsuarioRol { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> fechaCreacion { get; set; }
    
        public virtual tblRol tblRol { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
