//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSolicitud()
        {
            this.tblConyugue = new HashSet<tblConyugue>();
            this.tblReferencia = new HashSet<tblReferencia>();
            this.tblRelSolicitudDocumento = new HashSet<tblRelSolicitudDocumento>();
            this.tblAval = new HashSet<tblAval>();
            this.tblCliente = new HashSet<tblCliente>();
        }
    
        public int idSolicitud { get; set; }
        public string folio { get; set; }
        public string score { get; set; }
        public string comentarioVendedor { get; set; }
        public string comentarioVerificador { get; set; }
        public Nullable<int> idEstatusSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idUsuarioCaptura { get; set; }
        public Nullable<int> idUsuarioVerificador { get; set; }
        public Nullable<System.DateTime> fechaVerificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConyugue> tblConyugue { get; set; }
        public virtual tblEstatusSolicitud tblEstatusSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferencia> tblReferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelSolicitudDocumento> tblRelSolicitudDocumento { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAval> tblAval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCliente> tblCliente { get; set; }
    }
}
