//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cycMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSolicitud()
        {
            this.tblAval = new HashSet<tblAval>();
            this.tblCliente = new HashSet<tblCliente>();
            this.tblConyugue = new HashSet<tblConyugue>();
            this.tblDocumento = new HashSet<tblDocumento>();
            this.tblReferencia = new HashSet<tblReferencia>();
            this.tblRelSolicitudVendedor = new HashSet<tblRelSolicitudVendedor>();
            this.tblRelSolicitudVerificador = new HashSet<tblRelSolicitudVerificador>();
        }
    
        public int idSolicitud { get; set; }
        public string folio { get; set; }
        public string score { get; set; }
        public string comentarioVendedor { get; set; }
        public string comentarioVerificador { get; set; }
        public Nullable<int> idEstatusSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAval> tblAval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCliente> tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConyugue> tblConyugue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumento> tblDocumento { get; set; }
        public virtual tblEstatusSolicitud tblEstatusSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferencia> tblReferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelSolicitudVendedor> tblRelSolicitudVendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelSolicitudVerificador> tblRelSolicitudVerificador { get; set; }
    }
}
